/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FleetMetrics {
  'roi' : number,
  'costAvoidance' : number,
  'totalSavings' : number,
  'falseAlarmCosts' : number,
  'confusionMatrix' : {
    'falsePositive' : bigint,
    'trueNegative' : bigint,
    'falseNegative' : bigint,
    'truePositive' : bigint,
  },
  'rocAuc' : number,
  'prAuc' : number,
}
export interface MaintenanceAction {
  'action' : string,
  'downtimeHours' : number,
  'cost' : number,
  'notes' : string,
  'timestamp' : Timestamp,
}
export interface SensorReading {
  'rpm' : number,
  'vibration' : number,
  'powerEfficiency' : number,
  'reactivePowerRatio' : number,
  'turbulenceIntensity' : number,
  'timestamp' : Timestamp,
  'gearboxTemp' : number,
  'drivetrainRatio' : number,
  'phaseCurrent' : number,
}
export type Timestamp = bigint;
export interface TurbineMetrics {
  'id' : string,
  'remainingUsefulLife' : number,
  'failureProbability' : number,
  'maintenanceEvents' : Array<MaintenanceAction>,
  'healthScore' : number,
  'sensorReadings' : Array<SensorReading>,
  'shapContributions' : Array<number>,
  'riskLevel' : string,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSensorReading' : ActorMethod<[string, SensorReading], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllTurbines' : ActorMethod<[], Array<TurbineMetrics>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFleetMetrics' : ActorMethod<[], FleetMetrics>,
  'getMaintenanceHistory' : ActorMethod<[string], Array<MaintenanceAction>>,
  'getTurbine' : ActorMethod<[string], TurbineMetrics>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeTurbine' : ActorMethod<[string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logMaintenanceAction' : ActorMethod<[string, MaintenanceAction], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateTurbineStatus' : ActorMethod<
    [string, number, string, number, number, Array<number>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];