/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const SensorReading = IDL.Record({
  'rpm' : IDL.Float64,
  'vibration' : IDL.Float64,
  'powerEfficiency' : IDL.Float64,
  'reactivePowerRatio' : IDL.Float64,
  'turbulenceIntensity' : IDL.Float64,
  'timestamp' : Timestamp,
  'gearboxTemp' : IDL.Float64,
  'drivetrainRatio' : IDL.Float64,
  'phaseCurrent' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MaintenanceAction = IDL.Record({
  'action' : IDL.Text,
  'downtimeHours' : IDL.Float64,
  'cost' : IDL.Float64,
  'notes' : IDL.Text,
  'timestamp' : Timestamp,
});
export const TurbineMetrics = IDL.Record({
  'id' : IDL.Text,
  'remainingUsefulLife' : IDL.Float64,
  'failureProbability' : IDL.Float64,
  'maintenanceEvents' : IDL.Vec(MaintenanceAction),
  'healthScore' : IDL.Float64,
  'sensorReadings' : IDL.Vec(SensorReading),
  'shapContributions' : IDL.Vec(IDL.Float64),
  'riskLevel' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
});
export const FleetMetrics = IDL.Record({
  'roi' : IDL.Float64,
  'costAvoidance' : IDL.Float64,
  'totalSavings' : IDL.Float64,
  'falseAlarmCosts' : IDL.Float64,
  'confusionMatrix' : IDL.Record({
    'falsePositive' : IDL.Int,
    'trueNegative' : IDL.Int,
    'falseNegative' : IDL.Int,
    'truePositive' : IDL.Int,
  }),
  'rocAuc' : IDL.Float64,
  'prAuc' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSensorReading' : IDL.Func([IDL.Text, SensorReading], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllTurbines' : IDL.Func([], [IDL.Vec(TurbineMetrics)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFleetMetrics' : IDL.Func([], [FleetMetrics], ['query']),
  'getMaintenanceHistory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MaintenanceAction)],
      ['query'],
    ),
  'getTurbine' : IDL.Func([IDL.Text], [TurbineMetrics], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeTurbine' : IDL.Func([IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logMaintenanceAction' : IDL.Func([IDL.Text, MaintenanceAction], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateTurbineStatus' : IDL.Func(
      [
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Vec(IDL.Float64),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const SensorReading = IDL.Record({
    'rpm' : IDL.Float64,
    'vibration' : IDL.Float64,
    'powerEfficiency' : IDL.Float64,
    'reactivePowerRatio' : IDL.Float64,
    'turbulenceIntensity' : IDL.Float64,
    'timestamp' : Timestamp,
    'gearboxTemp' : IDL.Float64,
    'drivetrainRatio' : IDL.Float64,
    'phaseCurrent' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MaintenanceAction = IDL.Record({
    'action' : IDL.Text,
    'downtimeHours' : IDL.Float64,
    'cost' : IDL.Float64,
    'notes' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const TurbineMetrics = IDL.Record({
    'id' : IDL.Text,
    'remainingUsefulLife' : IDL.Float64,
    'failureProbability' : IDL.Float64,
    'maintenanceEvents' : IDL.Vec(MaintenanceAction),
    'healthScore' : IDL.Float64,
    'sensorReadings' : IDL.Vec(SensorReading),
    'shapContributions' : IDL.Vec(IDL.Float64),
    'riskLevel' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  const FleetMetrics = IDL.Record({
    'roi' : IDL.Float64,
    'costAvoidance' : IDL.Float64,
    'totalSavings' : IDL.Float64,
    'falseAlarmCosts' : IDL.Float64,
    'confusionMatrix' : IDL.Record({
      'falsePositive' : IDL.Int,
      'trueNegative' : IDL.Int,
      'falseNegative' : IDL.Int,
      'truePositive' : IDL.Int,
    }),
    'rocAuc' : IDL.Float64,
    'prAuc' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSensorReading' : IDL.Func([IDL.Text, SensorReading], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllTurbines' : IDL.Func([], [IDL.Vec(TurbineMetrics)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFleetMetrics' : IDL.Func([], [FleetMetrics], ['query']),
    'getMaintenanceHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MaintenanceAction)],
        ['query'],
      ),
    'getTurbine' : IDL.Func([IDL.Text], [TurbineMetrics], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeTurbine' : IDL.Func([IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logMaintenanceAction' : IDL.Func([IDL.Text, MaintenanceAction], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateTurbineStatus' : IDL.Func(
        [
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Vec(IDL.Float64),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };